name: gamingbytez-enhancements
version: '${project.version}'
main: de.lazybytez.gamingbytezenhancements.EnhancementsPlugin
api-version: '1.21'
permissions:
  gamingbytez.minecartportals.admin:
    description: Allows management of Minecart Portals
    default: op
  gamingbytez.chatbot.admin:
    description: Allows management of the Chat Bot
    default: op
dependencies:
  server:
    Multiverse-Core:
      load: BEFORE
      required: false
